[book]
authors = ["Jim Keener"]
language = "en"
multilingual = false
src = "src"
title = "VSLC - Very Small Logic Controller"

[output.markdown]

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = true

[preprocessor.plantuml]
